//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DATVE
    {
        public int IDChiTiet { get; set; }
        public int IDDonDatVe { get; set; }
        public string ViTriGhe { get; set; }
        public decimal Gia { get; set; }
    
        public virtual DON_DAT_VE DON_DAT_VE { get; set; }
    }
}
