//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DON_DAT_VE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DON_DAT_VE()
        {
            this.CT_DATVE = new HashSet<CT_DATVE>();
            this.THANH_TOAN = new HashSet<THANH_TOAN>();
        }
    
        public int IDDonDatVe { get; set; }
        public int IDKhachHang { get; set; }
        public int IDXuatChieu { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public string TrangThaiDatVe { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DATVE> CT_DATVE { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual XUAT_CHIEU XUAT_CHIEU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THANH_TOAN> THANH_TOAN { get; set; }
    }
}
