//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIM()
        {
            this.BINH_LUAN = new HashSet<BINH_LUAN>();
            this.XUAT_CHIEU = new HashSet<XUAT_CHIEU>();
        }
    
        public int IDPhim { get; set; }
        public string TenPhim { get; set; }
        public string DaoDien { get; set; }
        public string TheLoai { get; set; }
        public int ThoiLuong { get; set; }
        public string TomTat { get; set; }
        public string TrangThai { get; set; }
        public string AnhBia { get; set; }
        public string AnhNen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BINH_LUAN> BINH_LUAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XUAT_CHIEU> XUAT_CHIEU { get; set; }
    }
}
