//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG_CHIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG_CHIEU()
        {
            this.XUAT_CHIEU = new HashSet<XUAT_CHIEU>();
        }
    
        public int IDPhong { get; set; }
        public int IDRap { get; set; }
        public string TenPhong { get; set; }
        public int SoLuongGhe { get; set; }
        public string LoaiPhong { get; set; }
    
        public virtual RAP_PHIM RAP_PHIM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XUAT_CHIEU> XUAT_CHIEU { get; set; }
    }
}
