//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phim.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyRapPhimEntities : DbContext
    {
        public QuanLyRapPhimEntities()
            : base("name=QuanLyRapPhimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BINH_LUAN> BINH_LUAN { get; set; }
        public virtual DbSet<CT_DATVE> CT_DATVE { get; set; }
        public virtual DbSet<DON_DAT_VE> DON_DAT_VE { get; set; }
        public virtual DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual DbSet<PHIM> PHIMs { get; set; }
        public virtual DbSet<PHONG_CHIEU> PHONG_CHIEU { get; set; }
        public virtual DbSet<RAP_PHIM> RAP_PHIM { get; set; }
        public virtual DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public virtual DbSet<THANH_TOAN> THANH_TOAN { get; set; }
        public virtual DbSet<TIN_TUC> TIN_TUC { get; set; }
        public virtual DbSet<XUAT_CHIEU> XUAT_CHIEU { get; set; }
    }
}
