//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XUAT_CHIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XUAT_CHIEU()
        {
            this.DON_DAT_VE = new HashSet<DON_DAT_VE>();
        }
    
        public int IDXuatChieu { get; set; }
        public int IDPhim { get; set; }
        public int IDPhong { get; set; }
        public System.DateTime NgayChieu { get; set; }
        public System.TimeSpan GioChieu { get; set; }
        public decimal GiaVe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DON_DAT_VE> DON_DAT_VE { get; set; }
        public virtual PHIM PHIM { get; set; }
        public virtual PHONG_CHIEU PHONG_CHIEU { get; set; }
    }
}
