//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class BINH_LUAN
    {
        public int IDBinhLuan { get; set; }
        public int IDPhim { get; set; }
        public string TenNguoiBinhLuan { get; set; }
        public Nullable<System.DateTime> NgayBinhLuan { get; set; }
        public string NoiDung { get; set; }
        public int SoSao { get; set; }
    
        public virtual PHIM PHIM { get; set; }
    }
}
