//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DON_DAT_VE
    {
        public DON_DAT_VE()
        {
            this.CT_DATVE = new HashSet<CT_DATVE>();
        }
    
        public int IDDonDatVe { get; set; }
        public int IDKhachHang { get; set; }
        public int IDXuatChieu { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public string TrangThaiDatVe { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual ICollection<CT_DATVE> CT_DATVE { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual XUAT_CHIEU XUAT_CHIEU { get; set; }
    }
}
