//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACH_HANG
    {
        public KHACH_HANG()
        {
            this.DON_DAT_VE = new HashSet<DON_DAT_VE>();
            this.TAI_KHOAN = new HashSet<TAI_KHOAN>();
        }
    
        public int IDKhachHang { get; set; }
        public string HoTen { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string MaKhach { get; set; }
        public System.DateTime NgayDangKy { get; set; }
    
        public virtual ICollection<DON_DAT_VE> DON_DAT_VE { get; set; }
        public virtual ICollection<TAI_KHOAN> TAI_KHOAN { get; set; }
    }
}
