//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class QuanLyRapPhimEntities : DbContext
    {
        public QuanLyRapPhimEntities()
            : base("name=QuanLyRapPhimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BINH_LUAN> BINH_LUAN { get; set; }
        public DbSet<CT_DATVE> CT_DATVE { get; set; }
        public DbSet<DON_DAT_VE> DON_DAT_VE { get; set; }
        public DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public DbSet<PHIM> PHIMs { get; set; }
        public DbSet<PHONG_CHIEU> PHONG_CHIEU { get; set; }
        public DbSet<RAP_PHIM> RAP_PHIM { get; set; }
        public DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public DbSet<THANH_TOAN> THANH_TOAN { get; set; }
        public DbSet<TIN_TUC> TIN_TUC { get; set; }
        public DbSet<XUAT_CHIEU> XUAT_CHIEU { get; set; }
    
        public virtual int sp_DangKyTaiKhoan(Nullable<int> iDKhachHang, string tenDangNhap, string matKhau, string loai)
        {
            var iDKhachHangParameter = iDKhachHang.HasValue ?
                new ObjectParameter("IDKhachHang", iDKhachHang) :
                new ObjectParameter("IDKhachHang", typeof(int));
    
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("Loai", loai) :
                new ObjectParameter("Loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DangKyTaiKhoan", iDKhachHangParameter, tenDangNhapParameter, matKhauParameter, loaiParameter);
        }
    
        public virtual ObjectResult<sp_DangNhap_Result> sp_DangNhap(string tenDangNhap, string matKhau)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DangNhap_Result>("sp_DangNhap", tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<sp_DatVe_Result> sp_DatVe(Nullable<int> iDKhachHang, Nullable<int> iDXuatChieu, string danhSachGhe)
        {
            var iDKhachHangParameter = iDKhachHang.HasValue ?
                new ObjectParameter("IDKhachHang", iDKhachHang) :
                new ObjectParameter("IDKhachHang", typeof(int));
    
            var iDXuatChieuParameter = iDXuatChieu.HasValue ?
                new ObjectParameter("IDXuatChieu", iDXuatChieu) :
                new ObjectParameter("IDXuatChieu", typeof(int));
    
            var danhSachGheParameter = danhSachGhe != null ?
                new ObjectParameter("DanhSachGhe", danhSachGhe) :
                new ObjectParameter("DanhSachGhe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DatVe_Result>("sp_DatVe", iDKhachHangParameter, iDXuatChieuParameter, danhSachGheParameter);
        }
    
        public virtual int sp_DoiMatKhau(Nullable<int> iDTaiKhoan, string matKhauMoi)
        {
            var iDTaiKhoanParameter = iDTaiKhoan.HasValue ?
                new ObjectParameter("IDTaiKhoan", iDTaiKhoan) :
                new ObjectParameter("IDTaiKhoan", typeof(int));
    
            var matKhauMoiParameter = matKhauMoi != null ?
                new ObjectParameter("MatKhauMoi", matKhauMoi) :
                new ObjectParameter("MatKhauMoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DoiMatKhau", iDTaiKhoanParameter, matKhauMoiParameter);
        }
    
        public virtual ObjectResult<sp_GetBinhLuanTheoPhim_Result> sp_GetBinhLuanTheoPhim(Nullable<int> iDPhim)
        {
            var iDPhimParameter = iDPhim.HasValue ?
                new ObjectParameter("IDPhim", iDPhim) :
                new ObjectParameter("IDPhim", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetBinhLuanTheoPhim_Result>("sp_GetBinhLuanTheoPhim", iDPhimParameter);
        }
    
        public virtual ObjectResult<sp_GetChiTietDonVe_Result> sp_GetChiTietDonVe(Nullable<int> iDDonDatVe)
        {
            var iDDonDatVeParameter = iDDonDatVe.HasValue ?
                new ObjectParameter("IDDonDatVe", iDDonDatVe) :
                new ObjectParameter("IDDonDatVe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetChiTietDonVe_Result>("sp_GetChiTietDonVe", iDDonDatVeParameter);
        }
    
        public virtual ObjectResult<sp_GetPhongChieuByRap_Result> sp_GetPhongChieuByRap(Nullable<int> iDRap)
        {
            var iDRapParameter = iDRap.HasValue ?
                new ObjectParameter("IDRap", iDRap) :
                new ObjectParameter("IDRap", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPhongChieuByRap_Result>("sp_GetPhongChieuByRap", iDRapParameter);
        }
    
        public virtual ObjectResult<sp_GetTinTucMoiNhat_Result> sp_GetTinTucMoiNhat(Nullable<int> soLuong)
        {
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetTinTucMoiNhat_Result>("sp_GetTinTucMoiNhat", soLuongParameter);
        }
    
        public virtual int sp_HuyDonVe(Nullable<int> iDDonDatVe)
        {
            var iDDonDatVeParameter = iDDonDatVe.HasValue ?
                new ObjectParameter("IDDonDatVe", iDDonDatVe) :
                new ObjectParameter("IDDonDatVe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HuyDonVe", iDDonDatVeParameter);
        }
    
        public virtual int sp_KhoaTaiKhoan(Nullable<int> iDTaiKhoan)
        {
            var iDTaiKhoanParameter = iDTaiKhoan.HasValue ?
                new ObjectParameter("IDTaiKhoan", iDTaiKhoan) :
                new ObjectParameter("IDTaiKhoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_KhoaTaiKhoan", iDTaiKhoanParameter);
        }
    
        public virtual ObjectResult<string> sp_KiemTraGheDaDat(Nullable<int> iDXuatChieu)
        {
            var iDXuatChieuParameter = iDXuatChieu.HasValue ?
                new ObjectParameter("IDXuatChieu", iDXuatChieu) :
                new ObjectParameter("IDXuatChieu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_KiemTraGheDaDat", iDXuatChieuParameter);
        }
    
        public virtual int sp_MoKhoaTaiKhoan(Nullable<int> iDTaiKhoan)
        {
            var iDTaiKhoanParameter = iDTaiKhoan.HasValue ?
                new ObjectParameter("IDTaiKhoan", iDTaiKhoan) :
                new ObjectParameter("IDTaiKhoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MoKhoaTaiKhoan", iDTaiKhoanParameter);
        }
    
        public virtual int sp_ThanhToanDonVe(Nullable<int> iDDonDatVe)
        {
            var iDDonDatVeParameter = iDDonDatVe.HasValue ?
                new ObjectParameter("IDDonDatVe", iDDonDatVe) :
                new ObjectParameter("IDDonDatVe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThanhToanDonVe", iDDonDatVeParameter);
        }
    
        public virtual int sp_ThemBinhLuan(Nullable<int> iDPhim, string tenNguoiBinhLuan, string noiDung, Nullable<int> soSao)
        {
            var iDPhimParameter = iDPhim.HasValue ?
                new ObjectParameter("IDPhim", iDPhim) :
                new ObjectParameter("IDPhim", typeof(int));
    
            var tenNguoiBinhLuanParameter = tenNguoiBinhLuan != null ?
                new ObjectParameter("TenNguoiBinhLuan", tenNguoiBinhLuan) :
                new ObjectParameter("TenNguoiBinhLuan", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var soSaoParameter = soSao.HasValue ?
                new ObjectParameter("SoSao", soSao) :
                new ObjectParameter("SoSao", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemBinhLuan", iDPhimParameter, tenNguoiBinhLuanParameter, noiDungParameter, soSaoParameter);
        }
    
        public virtual ObjectResult<sp_ThongKeDoanhThu_Result> sp_ThongKeDoanhThu(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, Nullable<int> iDRap)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var iDRapParameter = iDRap.HasValue ?
                new ObjectParameter("IDRap", iDRap) :
                new ObjectParameter("IDRap", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeDoanhThu_Result>("sp_ThongKeDoanhThu", tuNgayParameter, denNgayParameter, iDRapParameter);
        }
    
        public virtual ObjectResult<sp_TimKhachHang_Result> sp_TimKhachHang(string email, string soDienThoai)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var soDienThoaiParameter = soDienThoai != null ?
                new ObjectParameter("SoDienThoai", soDienThoai) :
                new ObjectParameter("SoDienThoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKhachHang_Result>("sp_TimKhachHang", emailParameter, soDienThoaiParameter);
        }
    
        public virtual ObjectResult<sp_GetVeCuaToi_Result> sp_GetVeCuaToi(Nullable<int> iDKhachHang)
        {
            var iDKhachHangParameter = iDKhachHang.HasValue ?
                new ObjectParameter("IDKhachHang", iDKhachHang) :
                new ObjectParameter("IDKhachHang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetVeCuaToi_Result>("sp_GetVeCuaToi", iDKhachHangParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_HuyVeCuaToi(Nullable<int> iDDonDatVe, Nullable<int> iDKhachHang)
        {
            var iDDonDatVeParameter = iDDonDatVe.HasValue ?
                new ObjectParameter("IDDonDatVe", iDDonDatVe) :
                new ObjectParameter("IDDonDatVe", typeof(int));
    
            var iDKhachHangParameter = iDKhachHang.HasValue ?
                new ObjectParameter("IDKhachHang", iDKhachHang) :
                new ObjectParameter("IDKhachHang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_HuyVeCuaToi", iDDonDatVeParameter, iDKhachHangParameter);
        }
    }
}
