//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG_CHIEU
    {
        public PHONG_CHIEU()
        {
            this.XUAT_CHIEU = new HashSet<XUAT_CHIEU>();
        }
    
        public int IDPhong { get; set; }
        public int IDRap { get; set; }
        public string TenPhong { get; set; }
        public int SoLuongGhe { get; set; }
        public string LoaiPhong { get; set; }
    
        public virtual RAP_PHIM RAP_PHIM { get; set; }
        public virtual ICollection<XUAT_CHIEU> XUAT_CHIEU { get; set; }
    }
}
