//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyRapPhimEntities : DbContext
    {
        public QuanLyRapPhimEntities()
            : base("name=QuanLyRapPhimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BINH_LUAN> BINH_LUAN { get; set; }
        public DbSet<CT_DATVE> CT_DATVE { get; set; }
        public DbSet<DON_DAT_VE> DON_DAT_VE { get; set; }
        public DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public DbSet<PHIM> PHIM { get; set; }
        public DbSet<PHONG_CHIEU> PHONG_CHIEU { get; set; }
        public DbSet<RAP_PHIM> RAP_PHIM { get; set; }
        public DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public DbSet<TIN_TUC> TIN_TUC { get; set; }
        public DbSet<XUAT_CHIEU> XUAT_CHIEU { get; set; }
    }
}
