//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAP_PHIM
    {
        public RAP_PHIM()
        {
            this.PHONG_CHIEU = new HashSet<PHONG_CHIEU>();
        }
    
        public int IDRap { get; set; }
        public string TenRap { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<PHONG_CHIEU> PHONG_CHIEU { get; set; }
    }
}
