//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANH_TOAN
    {
        public int IDThanhToan { get; set; }
        public int IDDonDatVe { get; set; }
        public string PhuongThuc { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
    
        public virtual DON_DAT_VE DON_DAT_VE { get; set; }
    }
}
