//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIN_TUC
    {
        public int IDTinTuc { get; set; }
        public string TieuDe { get; set; }
        public string AnhBia { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
    }
}
